### ISSUE TITLE
TTS plugin invisible in shadow Jar

### ISSUE THREAD

**Issue by alexanderkoller** [dialogos-project/dialogos#126]
As of 79d113c88be477800ca5849935069ccfc42efc76, a shadow Jar that contains all the parts of Core DialogOS can be built as follows:

```
./gradlew shadowJar
```

This creates a file `build/libs/dialogos-with-dependencies-<VERSION>.jar` that can be executed with

```
java -jar build/libs/dialogos-with-dependencies-<VERSION>.jar
```

However, the GUI only displays the nodes of the speech recognizer plugin, not of the speech synthesis plugin in the node palette. This despite the fact that (a) the MaryTTS `Plugin` class is contained in the shadow Jar and (b) the `META-INF/services/com.clt.dialogos.plugin.Plugin` mentions both the ASR and the TTS plugin.

We should figure out why and fix it.

**Comment by timobaumann** [comment]
I just tested this and it now fails with
```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at de.saar.coli.dialogos.marytts.plugin.Settings.<init>(Settings.java:48)
	at de.saar.coli.dialogos.marytts.plugin.Plugin.createDefaultSettings(Plugin.java:62)
	at com.clt.diamant.SingleDocument.<init>(SingleDocument.java:295)
	at com.clt.diamant.Main.createNewDocument(Main.java:429)
	at com.clt.diamant.Main.doCommand(Main.java:459)
	at com.clt.diamant.gui.ProjectStartupFrame$2.run(ProjectStartupFrame.java:51)
	at com.clt.util.AbstractAction.actionPerformed(AbstractAction.java:141)
```

**Comment by timobaumann** [comment]
```java
                        .toArray(new VoiceName[voices.size()]), voices.get(0)) {
```
`voices` appears to be empty.

**Comment by timobaumann** [comment]
there's multiple copies of `META-INF/services/marytts.config.MaryConfig` in the file, presumably all overwriting each other. The shadowing seems to do a bad job of concatenating (or otherwise aggregating) these and we end up with an incomplete copy (I keep forgetting whether the classloader uses the first or last or any random copy).

**Comment by alexanderkoller** [comment]
Hm, that's progress, I suppose?

**Comment by akoehn** [comment]
[The merge strategy can be configured for the shadow gradle plugin](https://imperceptiblethoughts.com/shadow/configuration/merging/#merging-service-descriptor-files). The best strategy would probably to unzip the jar, modify the file to a hopefully good version, see whether that works and then try to pick a merge strategy (propably append?) that automatically creates such a version.

**Comment by timobaumann** [comment]
I believe we're just more eagerly checking for exceptions while loading plugins, so this new exception indeed is progress.
Any ideas how/if marytts builds shadow-jars? We should probably do the same. @psibre?

**Comment by timobaumann** [comment]
Fixed with ef4dffa . However, see https://fatjar.net/
