### ISSUE TITLE
dialogos (the non-distribution one) traceback w. ./gradlew run

### ISSUE THREAD

**Issue by akoehn** [dialogos-project/dialogos#192]
Seems to have something to to with the pocketsphinx plugin.  I didn't even know that we still had that!
```
Exception in thread "main" java.util.ServiceConfigurationError: com.clt.dialogos.plugin.Plugin: de.saar.coli.dialogos.pocketsphinx.plugin.Plugin Unable to get public no-arg constructor
        at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:581)
        at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:672)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1232)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1264)
        at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299)
        at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1384)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
        at com.clt.dialogos.plugin.PluginLoader.getPlugins(PluginLoader.java:22)
        at com.clt.dialogos.plugin.PluginLoader.getNumberOfPlugins(PluginLoader.java:31)
        at com.clt.dialogos.DialogOS.run(DialogOS.java:137)
        at com.clt.dialogos.DialogOS.main(DialogOS.java:107)
Caused by: java.lang.NoClassDefFoundError: org/json/simple/parser/ParseException
        at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
        at java.base/java.lang.Class.getConstructor0(Class.java:3342)
        at java.base/java.lang.Class.getConstructor(Class.java:2151)
        at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:659)
        at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:656)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:667)
        ... 9 more
Caused by: java.lang.ClassNotFoundException: org.json.simple.parser.ParseException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
```

**Comment by timobaumann** [comment]
it should certainly not be part of a standard build. what are you building from, dialogos-distribution? have you changed anything wrt the build process?

**Comment by akoehn** [comment]
Seems like my dialogos repository was not clean enough.  Does not happen with a fresh clone.

**Comment by timobaumann** [comment]
but that's a good remark: you need to do `./gradlew clean` before removing/commenting a plugin from `settings.gradle`. Otherwise the code won't be re-build nor cleaned later but the old build still ends up visible to DialogOS.
