### ISSUE TITLE
ROS plugin throws NPE

### ISSUE THREAD

**Issue by alexanderkoller** [dialogos-project/dialogos#206]
I get the following error when I run DialogOS from dialogos-distribution and then click on "Create New Dialog". DialogOS shows a popup ("The command could not be completed ..."). As a consequence, I currently cannot create dialogs on my computer (MacOS 10.14.5, Java 1.8).

```
dhcp104-196:dialogos-distribution koller$ ./gradlew clean run
[...]
java.lang.NullPointerException
        at app.dialogos.ros.plugin.ROSPluginSettings.getenv(ROSPluginSettings.java:51)
        at app.dialogos.ros.plugin.ROSPluginSettings.<init>(ROSPluginSettings.java:29)
        at app.dialogos.ros.plugin.ROSPlugin.createDefaultSettings(ROSPlugin.java:39)
        at com.clt.diamant.SingleDocument.<init>(SingleDocument.java:294)
        at com.clt.diamant.Main.createNewDocument(Main.java:429)
        at com.clt.diamant.Main.doCommand(Main.java:459)
        at com.clt.diamant.gui.ProjectStartupFrame$2.run(ProjectStartupFrame.java:51)
        at com.clt.util.AbstractAction.actionPerformed(AbstractAction.java:141)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
        at java.awt.Component.processMouseEvent(Component.java:6533)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
        at java.awt.Component.processEvent(Component.java:6298)
        at java.awt.Container.processEvent(Container.java:2236)
        at java.awt.Component.dispatchEventImpl(Component.java:4889)
        at java.awt.Container.dispatchEventImpl(Container.java:2294)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
        at java.awt.Container.dispatchEventImpl(Container.java:2280)
        at java.awt.Window.dispatchEventImpl(Window.java:2746)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.awt.EventQueue$4.run(EventQueue.java:729)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Any idea why? 

I am using the current dialogos-distribution (after git pull; last commit is from June). Does anyone know why all the dependencies in the build.gradle point to 2.1.0, when the current release is 2.1.3? Could this be part of this problem?

**Comment by timobaumann** [comment]
`git checkout 2.1.3` should clarify whether it's some issue in master.

**Comment by timobaumann** [comment]
works for me in 2.1.3

**Comment by timobaumann** [comment]
issue with build.gradle pointing to 2.1.0 seems to be in the way the release process works.

**Comment by alexanderkoller** [comment]
Interesting, after gradle clean that worked for me too.

Is it intended behavior that we need to switch to a branch in order to run dialogos-distribution?

**Comment by timobaumann** [comment]
somewhere between intended/neglected and a bug in our releaes process (we push a branch/tag but we do not update master). Oh well.

**Comment by alexanderkoller** [comment]
Added a bit of documentation to the README of dialogos-distribution.
