### ISSUE TITLE
NxtUsb loses connection

### ISSUE THREAD

**Issue by alexanderkoller** [dialogos-project/dialogos#39]
On MacOS Sierra, I intermittently get exceptions like this one when an NXT node is executed:

```
Error at node
   NXT Motor
in legoanaus.xml
javax.usb.UsbNotClaimedException: Interface is not claimed.
        at org.usb4java.javax.Pipe.checkClaimed(Pipe.java:90)
        at org.usb4java.javax.Pipe.open(Pipe.java:120)
        at com.clt.lego.nxt.NxtUsb.send(NxtUsb.java:307)
        at com.clt.lego.nxt.NxtUsb.sendDirectCommand(NxtUsb.java:258)
        at com.clt.lego.nxt.AbstractNxt.setOutputState(AbstractNxt.java:538)
        at com.clt.lego.nxt.Motor.forward(Motor.java:113)
        at com.clt.dialogos.lego.nxt.nodes.MotorNode.executeNXT(MotorNode.java:112)
        at com.clt.dialogos.lego.nxt.Node.execute(Node.java:42)
        at com.clt.diamant.graph.Graph.execute(Graph.java:341)
        at com.clt.diamant.SingleDocument.execute(SingleDocument.java:476)
        at com.clt.diamant.SingleDocument.run(SingleDocument.java:403)
        at com.clt.diamant.gui.SingleDocumentWindow$11.run(SingleDocumentWindow.java:829)
        at java.base/java.lang.Thread.run(Thread.java:844)
```

This happens after the interface had been previously claimed, in the same run of the dialogue.

Is it safe to simply reclaim the interface if this exception occurs?

**Comment by alexanderkoller** [comment]
Given the upcoming release of the EV3 plugin, this is probably not important any more.
